
//function to create random color 
const makeRandColor = () => {
    const r = Math.floor(Math.random() * 255);
    const g = Math.floor(Math.random() * 255);
    const b = Math.floor(Math.random() * 255);
    return `rgb(${r}, ${g}, ${b})`;
}


const buttons=document.querySelectorAll('button') //select all buttons 

for (let button of buttons){
    button.addEventListener('click', function(){
        //set background color to result of random color
        button.style.backgroundColor=makeRandColor();
        button.style.color=makeRandColor();
    })
}

//select all h1s
const h1s=document.querySelectorAll('h1')

//loop through h1s
for(let h1 of h1s){
    //add event listner
    h1.addEventListener('click',function(){
        //change color of text to random color generated by function
        h1.style.color=makeRandColor()
    })
}
